### ISSUE TITLE
not show hsl colours

### ISSUE THREAD

**Issue by dobbbri** [DeMoorJasper/vscode-pigments#1]
and in stylus so!!
like:

$turquoise = hsl(168, 76%, 42%)
$greenSea = hsl(168, 76%, 36%)
$nephritis = hsl(145, 63%, 42%)
$emerald = hsl(145, 63%, 49%)
$sunFlower = hsl(48, 89%, 50%)
$orange = hsl(37, 90%, 51%)
$carrot = hsl(28, 80%, 52%)
$pumpkin = hsl(24, 100%, 41%)
$alizarin = hsl(6, 78%, 57%)
$pomegranate = hsl(6, 63%, 46%)
$amethyst = hsl(283, 39%, 53%)
$wisteria = hsl(282, 44%, 47%)
$belizeHole = hsl(204, 64%, 44%)
$peterRiver = hsl(204, 70%, 53%)
$white = hsl(0, 0%, 100%)
$clouds = hsl(192, 15%, 94%)
$silver = hsl(204, 8%, 76%)
$concrete = hsl(184, 9%, 62%)
$asbestos = hsl(184, 6%, 53%)
$wetAsphalt = hsl(210, 29%, 29%)
$midnightBlue = hsl(210, 29%, 24%)
$black = hsl(0, 0%, 0%)

**Comment by DeMoorJasper** [comment]
Thanks for the report i'll fix this asap

**Comment by DeMoorJasper** [comment]
Fixed and released in 0.0.5
