### ISSUE TITLE
Please publish the extension to OpenVSX

### ISSUE THREAD

**Issue by entepe85** [DeMoorJasper/vscode-pigments#11]
I'm a [VS Codium](https://github.com/VSCodium/vscodium) user, a FLOSS version of VS Code. It's the same code but without Microsoft's telemetry, branding and licensing.

I would like to request, if possible, to add the vscode-pigments extension to the [open-vsx.org](https://open-vsx.org) market as it is unclear if it's legal to use the official Microsoft extension marketplace on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168).

Additional information on how to publish an extension to Open VSX can be obtained [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by DeMoorJasper** [comment]
Will look into that later today, pretty annoying that there's legal issues with downloading mostly open-source and free extensions.

**Comment by entepe85** [comment]
Well, I tried my hand at cloning and publishing the extension to OpenVSX and obviously succeeded in doing so:
https://open-vsx.org/extension/jaspernorth/vscode-pigments

I chose to publish it under your namespace and would advise you to [claim it](https://github.com/eclipse/openvsx/wiki/Namespace-Access), if possible.

**Comment by DeMoorJasper** [comment]
@entepe85 thanks for doing that, got busy with other things and publishing to open-vsx was't really that straightforward
