### ISSUE TITLE
Cake addin declarations are being colorized when they shouldn't be

### ISSUE THREAD

**Issue by xt0rted** [DeMoorJasper/vscode-pigments#2]
![image](https://user-images.githubusercontent.com/831974/39412534-c900e0de-4beb-11e8-8358-187cbdb9dc24.png)

To repro create a file called `build.cake` and add the folowing text to it:

```cake
#addin nuget:?package=Cake.Bower&version=0.5.0
#addin nuget:?package=Cake.FileHelpers&version=2.0.0
#addin nuget:?package=Cake.Gulp&version=0.8.0
#addin nuget:?package=Cake.Incubator&version=1.7.2
#addin nuget:?package=Cake.Npm&version=0.12.1
#addin nuget:?package=Cake.XdtTransform&version=0.12.1
#addin nuget:?package=Diff4Net&version=1.2.0
```

A full example file can be found at https://github.com/cake-build/cake/blob/develop/build.cake

**Comment by DeMoorJasper** [comment]
Expected this issue sooner or later, I've pushed an extension whitelist, should be fixed now

**Comment by xt0rted** [comment]
Can confirm, issue's gone in the `.cake` files. Thanks for the update and the extension.
