### ISSUE TITLE
Doesn't render RRGGBBAA

### ISSUE THREAD

**Issue by jdmunro** [DeMoorJasper/vscode-pigments#4]
I noticed that rgba is rendering correctly:

<img width="501" alt="screen shot 2018-09-05 at 08 57 32" src="https://user-images.githubusercontent.com/17656/45079342-369e9b00-b0ea-11e8-8261-9ccdc9e9a63f.png">

But when I convert this to RRGGBBAA it doesn't recognise the alpha portion of the color:

<img width="391" alt="screen shot 2018-09-05 at 08 57 03" src="https://user-images.githubusercontent.com/17656/45079363-46b67a80-b0ea-11e8-9a3f-05af2754cc7f.png">

https://hashnode.com/post/understanding-rrggbbaa-color-notation-cisvdr52x088fwt53h1drf6m2

**Comment by DeMoorJasper** [comment]
I didn't even know that was a thing, It's just a minor change to the regex.

https://github.com/DeMoorJasper/vscode-pigments/blob/master/src/extension.ts#L6

Feel free to edit it yourself, otherwise I'll change the 6 into an 8 somewhere tonight

**Comment by DeMoorJasper** [comment]
Please review #5

**Comment by jdmunro** [comment]
Nice @DeMoorJasper 👍
