### ISSUE TITLE
Highlights my element ids

### ISSUE THREAD

**Issue by brandonkal** [DeMoorJasper/vscode-pigments#6]
When this plugin is active, it highlights folders too aggressively. For instance, it highlights element ID names. As an example, if I have this rule:
```
#featured-media button:hover {
  background: #00a6e4;
}
```
pigments decides to highlight `#fea`

This also occurs in Javascript files as well:
```
$('#caret').addClass('fa-angle-down')
```
Where `#ca` is highlighted.
Pigments should consider word boundaries to avoid these issues.

**Comment by DeMoorJasper** [comment]
It's basically just a regex thing, feel free to change it and open up a PR.
I'll try look into this asap if you're not interested in contributing.
https://github.com/DeMoorJasper/vscode-pigments/blob/master/src/extension.ts#L6

**Comment by brandonkal** [comment]
@DeMoorJasper I figured it was something relatively simple. I found another extension without the false positives when I opened this issue so I won't find the time for a PR, but thought I would still bring it to your attention.

**Comment by Braintelligence** [comment]
@brandonkal Please add which extension you switched to. I'm also suffering from this and need to switch to something else; it's just unusable if you code HTML ids.

**Comment by DeMoorJasper** [comment]
6d58c406010d6ba570ca91ed2bfac8b912b19e9e should add some kind of boundary to prevent this, will test this a bit further and release an update in a couple hours
