### ISSUE TITLE
Add HSL / HSLA

### ISSUE THREAD

**Issue by Horttcore** [DeMoorJasper/vscode-pigments#8]
HSL and HSLA support is missing :-(

![image](https://user-images.githubusercontent.com/503252/63972795-c383f680-caa9-11e9-9602-d34449fbff0e.png)

**Comment by DeMoorJasper** [comment]
It should already support hsl, but in the regex it's lowercase and case-sensitive so it's not catching it.

https://github.com/DeMoorJasper/vscode-pigments/blob/master/src/extension.ts#L6

**Comment by DeMoorJasper** [comment]
Reopened it as I'll update the regex to support hsla and no longer be case sensitive

**Comment by Horttcore** [comment]
@DeMoorJasper ok thanks I was to fast then :-)

**Comment by DeMoorJasper** [comment]
Fixed it in f081429680a3a2d2d57275c2152e161e523e19ac will try get a v2 release out today with a bunch of fixes and new features
